#!/bin/bash
# Formula search for the attention gauge (gauge_formula.py validate): scores gauges of known CROWN quality + weight-only candidates
# on sst_bert_small_6.   gauge_formula_chain.sh smoke | full
set -u
REPO="/mmfs1/gscratch/scrubbed/sgvtc/E-graphs for Verifiability"; S="$REPO/NNs/vit_rewrite/_scratch"; PY="$REPO/alpha-beta-CROWN/.venv/bin/python"
T="$REPO/NNs/transformer_rewrite"; export OMP_NUM_THREADS=4 PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True; cd "$T"
W=$1; G="gauges"   # relative: the repo path contains spaces and $ARGS is word-split
ALL="$G/deept_small6_seed0.pt,$G/deept_small6_oodyelp_seed0.pt,$G/deept_small6_oodrandom_seed0.pt,$G/deept_small6_2w_seed0.pt,$G/pbvtrained_small6_inner_seed0.pt,$G/pbvtrained_small6_origin_seed0.pt"
mark() { echo "$1 formula_$W $(date) job=${SLURM_JOB_ID:-none}" >> "$S/official_sequence.log"; }
case $W in
  smoke) ARGS="--n_sent 2 --pos 1 --n_sst 4 --l1_steps 20 --hi 0.05 --gauges $G/deept_small6_seed0.pt,$G/pbvtrained_small6_origin_seed0.pt"; OUT="$T/results/formula_small6_smoke.json" ;;
  full)  ARGS="--n_sent 12 --pos 2 --n_sst 48 --l1_steps 400 --hi 0.1 --gauges $ALL"; OUT="$T/results/formula_small6_validate.json" ;;
  big3)  NAME=sst_bert_big_3;   ARGS="--n_sent 12 --pos 2 --n_sst 48 --l1_steps 400 --hi 0.1 --gauges $G/deept_big3_seed0.pt";  OUT="$T/results/formula_big3_validate.json" ;;
  yelp3) NAME=yelp_bert_small_3; ARGS="--n_sent 12 --pos 2 --n_sst 48 --l1_steps 400 --hi 0.1 --gauges $G/deept_yelp3_seed0.pt"; OUT="$T/results/formula_yelp3_validate.json" ;;
  yelp3_big) NAME=yelp_bert_small_3; ARGS="--n_sent 48 --pos 2 --n_sst 48 --l1_steps 100 --hi 0.1 --gauges $G/deept_yelp3_seed0.pt"; OUT="$T/results/formula_yelp3_validate_96box.json" ;;   # 4x the probes: does averaging remove the probe-seed dependence?
  # ---- improvement goal (2026-09-07 eve): localisation hybrids, probe-seed cross, unlabeled dev-text probes, held-out radius screen
  hyb_yelp3)  NAME=yelp_bert_small_3; ARGS="--n_sent 48 --pos 2 --n_sst 48 --l1_steps 0 --hi 0.1 --hybrids 1 --cross 1 --radius_names auto --n_dev 24 --dev_probes 48 --tag _h --gauges $G/deept_yelp3_seed0.pt";  OUT="$T/results/formula_yelp3_hyb.json" ;;
  hyb_small6) NAME=sst_bert_small_6;  ARGS="--n_sent 12 --pos 2 --n_sst 48 --l1_steps 0 --hi 0.1 --hybrids 1 --cross 0 --radius_names auto --n_dev 24 --dev_probes 24 --tag _h --gauges $G/deept_small6_seed0.pt"; OUT="$T/results/formula_small6_hyb.json" ;;
  hyb_big3)   NAME=sst_bert_big_3;    ARGS="--n_sent 12 --pos 2 --n_sst 48 --l1_steps 0 --hi 0.1 --hybrids 1 --cross 0 --radius_names auto --n_dev 24 --dev_probes 24 --tag _h --gauges $G/deept_big3_seed0.pt";   OUT="$T/results/formula_big3_hyb.json" ;;
  smoke_hyb)  NAME=yelp_bert_small_3; ARGS="--n_sent 2 --pos 1 --n_sst 4 --l1_steps 0 --hi 0.05 --hybrids 1 --cross 1 --radius_names auto --n_dev 2 --dev_probes 2 --tag _smoke --gauges $G/deept_yelp3_seed0.pt"; OUT="$T/results/formula_hyb_smoke.json" ;;
  # ---- round 2: sensitivity-weighted token blocks (--sens) and CROWN-inflation rescaling of M (--infl), held-out radius screen
  r2_yelp3)  NAME=yelp_bert_small_3; ARGS="--n_sent 48 --pos 2 --n_sst 48 --l1_steps 0 --hi 0.1 --sens 1 --infl 3 --radius_names auto --n_dev 24 --tag _r2 --gauges $G/deept_yelp3_seed0.pt";  OUT="$T/results/formula_yelp3_r2.json" ;;
  r2_small6) NAME=sst_bert_small_6;  ARGS="--n_sent 12 --pos 2 --n_sst 48 --l1_steps 0 --hi 0.1 --sens 1 --infl 3 --radius_names auto --n_dev 24 --tag _r2 --gauges $G/deept_small6_seed0.pt"; OUT="$T/results/formula_small6_r2.json" ;;
  r2_big3)   NAME=sst_bert_big_3;    ARGS="--n_sent 12 --pos 2 --n_sst 48 --l1_steps 0 --hi 0.1 --sens 1 --infl 3 --radius_names auto --n_dev 24 --tag _r2 --gauges $G/deept_big3_seed0.pt";   OUT="$T/results/formula_big3_r2.json" ;;
  smoke_r2)  NAME=yelp_bert_small_3; ARGS="--n_sent 2 --pos 1 --n_sst 4 --l1_steps 0 --hi 0.05 --sens 1 --infl 2 --radius_names auto --n_dev 2 --tag _smoke --gauges $G/deept_yelp3_seed0.pt"; OUT="$T/results/formula_r2_smoke.json" ;;
  # ---- round 3: the layer-0 width product is an l1 problem (one token block) -> l1 surrogate with N from the closed form (+ splices), held-out screen on SST test
  r3_yelp3)  NAME=yelp_bert_small_3; ARGS="--n_sent 48 --pos 2 --n_sst 48 --l1_steps 400 --l1N 1 --infl 1 --hi 0.1 --radius_names auto --n_dev 24 --tag _r3 --gauges $G/deept_yelp3_seed0.pt";  OUT="$T/results/formula_yelp3_r3.json" ;;
  r3_big3)   NAME=sst_bert_big_3;    ARGS="--n_sent 12 --pos 2 --n_sst 48 --l1_steps 400 --l1N 1 --infl 1 --hi 0.1 --radius_names auto --n_dev 24 --dev_split test --tag _r3 --gauges $G/deept_big3_seed0.pt";   OUT="$T/results/formula_big3_r3.json" ;;
  r3_small6) NAME=sst_bert_small_6;  ARGS="--n_sent 12 --pos 2 --n_sst 48 --l1_steps 400 --l1N 1 --infl 1 --hi 0.1 --radius_names auto --n_dev 24 --dev_split test --tag _r3 --gauges $G/deept_small6_seed0.pt"; OUT="$T/results/formula_small6_r3.json" ;;
  smoke_r3)  NAME=sst_bert_big_3;    ARGS="--n_sent 2 --pos 1 --n_sst 4 --l1_steps 20 --l1N 1 --infl 1 --hi 0.05 --radius_names auto --n_dev 2 --dev_split test --tag _smoke --gauges $G/deept_big3_seed0.pt"; OUT="$T/results/formula_r3_smoke.json" ;;
  # ---- round 4: longer, annealed l1N optimisation (1500 steps, cosine lr); explicit radius-screen list
  r4_yelp3)  NAME=yelp_bert_small_3; ARGS="--n_sent 48 --pos 2 --n_sst 48 --l1_steps 1500 --l1N 1 --hi 0.1 --radius_names identity,yelp3,cand:svd_jacN_all,cand:l1N,cand:l1N@L0 --n_dev 24 --tag _r4 --gauges $G/deept_yelp3_seed0.pt";  OUT="$T/results/formula_yelp3_r4.json" ;;
  r4_big3)   NAME=sst_bert_big_3;    ARGS="--n_sent 12 --pos 2 --n_sst 48 --l1_steps 1500 --l1N 1 --hi 0.1 --radius_names identity,big3,cand:svd_jacN_all,cand:l1N,cand:l1N@L0 --n_dev 24 --dev_split test --tag _r4 --gauges $G/deept_big3_seed0.pt";   OUT="$T/results/formula_big3_r4.json" ;;
  r4_small6) NAME=sst_bert_small_6;  ARGS="--n_sent 12 --pos 2 --n_sst 48 --l1_steps 1500 --l1N 1 --hi 0.1 --radius_names identity,small6,cand:svd_jacN_all,cand:l1N,cand:l1N@L0 --n_dev 24 --dev_split test --tag _r4 --gauges $G/deept_small6_seed0.pt"; OUT="$T/results/formula_small6_r4.json" ;;
  # ---- round 5: held-out screens of the unified rule (l1 QK everywhere, l1 AV at layer 0); Yelp also with a second probe seed
  r5_yelp3)    NAME=yelp_bert_small_3; ARGS="--n_sent 48 --pos 2 --n_sst 48 --l1_steps 400 --l1N 1 --hi 0.1 --radius_names identity,yelp3,cand:svd_jacN_all,cand:l1N,cand:l1N_qk,cand:l1N_qk+av0 --n_dev 24 --tag _r5 --gauges $G/deept_yelp3_seed0.pt";  OUT="$T/results/formula_yelp3_r5.json" ;;
  r5_yelp3_s1) NAME=yelp_bert_small_3; SEED=1; ARGS="--n_sent 48 --pos 2 --n_sst 48 --l1_steps 400 --l1N 1 --hi 0.1 --radius_names identity,yelp3,cand:svd_jacN_all,cand:l1N,cand:l1N_qk,cand:l1N_qk+av0 --n_dev 24 --tag _r5s1 --gauges $G/deept_yelp3_seed0.pt";  OUT="$T/results/formula_yelp3_r5_seed1.json" ;;
  r5_big3)     NAME=sst_bert_big_3;    ARGS="--n_sent 12 --pos 2 --n_sst 48 --l1_steps 400 --l1N 1 --hi 0.1 --radius_names identity,big3,cand:svd_jacN_all,cand:l1N,cand:l1N_qk,cand:l1N_qk+av0 --n_dev 24 --dev_split test --tag _r5 --gauges $G/deept_big3_seed0.pt";   OUT="$T/results/formula_big3_r5.json" ;;
  r5_small6)   NAME=sst_bert_small_6;  ARGS="--n_sent 12 --pos 2 --n_sst 48 --l1_steps 400 --l1N 1 --hi 0.1 --radius_names identity,small6,cand:svd_jacN_all,cand:l1N,cand:l1N_qk,cand:l1N_qk+av0 --n_dev 24 --dev_split test --tag _r5 --gauges $G/deept_small6_seed0.pt"; OUT="$T/results/formula_small6_r5.json" ;;
  # round 6: rotation-only l1N refinement of the closed form (cand:l1N_rot, cand:l1N_rot_qk+av0) vs the unified rule; same screens as r5
  smoke_r6)    NAME=sst_bert_big_3;    ARGS="--n_sent 2 --pos 1 --n_sst 4 --l1_steps 20 --l1N 1 --l1rot 1 --hi 0.05 --radius_names identity,big3,cand:l1N_qk+av0,cand:l1N_rot --n_dev 2 --dev_split test --tag _smoke6 --gauges $G/deept_big3_seed0.pt"; OUT="$T/results/formula_r6_smoke.json" ;;
  r6_big3)     NAME=sst_bert_big_3;    ARGS="--n_sent 12 --pos 2 --n_sst 48 --l1_steps 400 --l1N 1 --l1rot 1 --hi 0.1 --radius_names identity,big3,cand:svd_jacN_all,cand:l1N_qk+av0,cand:l1N_rot,cand:l1N_rot_qk+av0 --n_dev 24 --dev_split test --tag _r6 --gauges $G/deept_big3_seed0.pt";   OUT="$T/results/formula_big3_r6.json" ;;
  r6_yelp3)    NAME=yelp_bert_small_3; ARGS="--n_sent 48 --pos 2 --n_sst 48 --l1_steps 400 --l1N 1 --l1rot 1 --hi 0.1 --radius_names identity,yelp3,cand:svd_jacN_all,cand:l1N_qk+av0,cand:l1N_rot,cand:l1N_rot_qk+av0 --n_dev 24 --tag _r6 --gauges $G/deept_yelp3_seed0.pt";  OUT="$T/results/formula_yelp3_r6.json" ;;
  r6_yelp3_s1) NAME=yelp_bert_small_3; SEED=1; ARGS="--n_sent 48 --pos 2 --n_sst 48 --l1_steps 400 --l1N 1 --l1rot 1 --hi 0.1 --radius_names identity,yelp3,cand:svd_jacN_all,cand:l1N_qk+av0,cand:l1N_rot,cand:l1N_rot_qk+av0 --n_dev 24 --tag _r6s1 --gauges $G/deept_yelp3_seed0.pt";  OUT="$T/results/formula_yelp3_r6_seed1.json" ;;
  # label-conditioned manual rule: probes restricted to the model's predicted label (random tokens, n_sent 24 -> ~12 per class); screen = the usual 24 test sentences, split by label afterwards
  smoke_plab)   NAME=sst_bert_big_3;    ARGS="--n_sent 4 --pos 1 --n_sst 4 --l1_steps 20 --l1N 1 --probe_label 0 --hi 0.05 --radius_names identity,big3,cand:l1N_qk+av0 --n_dev 2 --dev_split test --tag _plabsmoke --gauges $G/deept_big3_seed0.pt"; OUT="$T/results/formula_plab_smoke.json" ;;
  plab0_big3)   NAME=sst_bert_big_3;    ARGS="--n_sent 24 --pos 2 --n_sst 48 --l1_steps 400 --l1N 1 --probe_label 0 --hi 0.1 --radius_names identity,big3,big3_lab0,cand:svd_jacN_all,cand:l1N_qk+av0 --n_dev 24 --dev_split test --tag _plab0 --gauges $G/deept_big3_seed0.pt,$G/deept_big3_lab0_seed0.pt";   OUT="$T/results/formula_big3_plab0.json" ;;
  plab1_big3)   NAME=sst_bert_big_3;    ARGS="--n_sent 24 --pos 2 --n_sst 48 --l1_steps 400 --l1N 1 --probe_label 1 --hi 0.1 --radius_names identity,big3,big3_lab1,cand:svd_jacN_all,cand:l1N_qk+av0 --n_dev 24 --dev_split test --tag _plab1 --gauges $G/deept_big3_seed0.pt,$G/deept_big3_lab1_seed0.pt";   OUT="$T/results/formula_big3_plab1.json" ;;
  plab0_small6) NAME=sst_bert_small_6;  ARGS="--n_sent 24 --pos 2 --n_sst 48 --l1_steps 400 --l1N 1 --probe_label 0 --hi 0.1 --radius_names identity,small6,small6_lab0,cand:svd_jacN_all,cand:l1N_qk+av0 --n_dev 24 --dev_split test --tag _plab0 --gauges $G/deept_small6_seed0.pt,$G/deept_small6_lab0_seed0.pt"; OUT="$T/results/formula_small6_plab0.json" ;;
  plab1_small6) NAME=sst_bert_small_6;  ARGS="--n_sent 24 --pos 2 --n_sst 48 --l1_steps 400 --l1N 1 --probe_label 1 --hi 0.1 --radius_names identity,small6,small6_lab1,cand:svd_jacN_all,cand:l1N_qk+av0 --n_dev 24 --dev_split test --tag _plab1 --gauges $G/deept_small6_seed0.pt,$G/deept_small6_lab1_seed0.pt"; OUT="$T/results/formula_small6_plab1.json" ;;
  # ---- sign-aware per-label rule (2026-09-10): cand:sgn / cand:sgn_qk built on CPU by cost_only --signed_steps (gauges/formula_<name>_sgn{,_qk}_lab<y>.pt), screened on the plab boxes (same seed -> same 24 sentences / 48 boxes)
  smoke_sgn)   NAME=sst_bert_small_6;  ARGS="--n_sent 4 --pos 1 --n_sst 4 --l1_steps 0 --probe_label 1 --hi 0.05 --radius_names identity,small6,formula_sst_bert_small_6_sgn_sgnsmoke --n_dev 2 --dev_split test --tag _sgnsmoke --gauges $G/deept_small6_seed0.pt,$G/formula_sst_bert_small_6_sgn_sgnsmoke.pt"; OUT="$T/results/formula_sgn_smoke.json" ;;
  sgn0_big3)   NAME=sst_bert_big_3; SG=$(ls $G/formula_sst_bert_big_3_sgn*_lab0.pt 2>/dev/null | tr "\n" ","); SN=$(ls $G/formula_sst_bert_big_3_sgn*_lab0.pt 2>/dev/null | xargs -n1 basename | sed "s/.pt$//" | tr "\n" ","); ARGS="--n_sent 24 --pos 2 --n_sst 48 --l1_steps 0 --probe_label 0 --hi 0.1 --radius_names identity,big3,big3_lab0,formula_sst_bert_big_3_l1N_qk_av0_r3,${SN%,} --n_dev 24 --dev_split test --tag _sgn0 --gauges $G/deept_big3_seed0.pt,$G/deept_big3_lab0_seed0.pt,$G/formula_sst_bert_big_3_l1N_qk_av0_r3.pt,${SG%,}"; OUT="$T/results/formula_big3_sgn0.json" ;;
  sgn1_big3)   NAME=sst_bert_big_3; SG=$(ls $G/formula_sst_bert_big_3_sgn*_lab1.pt 2>/dev/null | tr "\n" ","); SN=$(ls $G/formula_sst_bert_big_3_sgn*_lab1.pt 2>/dev/null | xargs -n1 basename | sed "s/.pt$//" | tr "\n" ","); ARGS="--n_sent 24 --pos 2 --n_sst 48 --l1_steps 0 --probe_label 1 --hi 0.1 --radius_names identity,big3,big3_lab1,formula_sst_bert_big_3_l1N_qk_av0_r3,${SN%,} --n_dev 24 --dev_split test --tag _sgn1 --gauges $G/deept_big3_seed0.pt,$G/deept_big3_lab1_seed0.pt,$G/formula_sst_bert_big_3_l1N_qk_av0_r3.pt,${SG%,}"; OUT="$T/results/formula_big3_sgn1.json" ;;
  sgn0_small6)   NAME=sst_bert_small_6; SG=$(ls $G/formula_sst_bert_small_6_sgn*_lab0.pt 2>/dev/null | tr "\n" ","); SN=$(ls $G/formula_sst_bert_small_6_sgn*_lab0.pt 2>/dev/null | xargs -n1 basename | sed "s/.pt$//" | tr "\n" ","); ARGS="--n_sent 24 --pos 2 --n_sst 48 --l1_steps 0 --probe_label 0 --hi 0.1 --radius_names identity,small6,small6_lab0,formula_sst_bert_small_6_l1N_qk_av0_r4,${SN%,} --n_dev 24 --dev_split test --tag _sgn0 --gauges $G/deept_small6_seed0.pt,$G/deept_small6_lab0_seed0.pt,$G/formula_sst_bert_small_6_l1N_qk_av0_r4.pt,${SG%,}"; OUT="$T/results/formula_small6_sgn0.json" ;;
  sgn1_small6)   NAME=sst_bert_small_6; SG=$(ls $G/formula_sst_bert_small_6_sgn*_lab1.pt 2>/dev/null | tr "\n" ","); SN=$(ls $G/formula_sst_bert_small_6_sgn*_lab1.pt 2>/dev/null | xargs -n1 basename | sed "s/.pt$//" | tr "\n" ","); ARGS="--n_sent 24 --pos 2 --n_sst 48 --l1_steps 0 --probe_label 1 --hi 0.1 --radius_names identity,small6,small6_lab1,formula_sst_bert_small_6_l1N_qk_av0_r4,${SN%,} --n_dev 24 --dev_split test --tag _sgn1 --gauges $G/deept_small6_seed0.pt,$G/deept_small6_lab1_seed0.pt,$G/formula_sst_bert_small_6_l1N_qk_av0_r4.pt,${SG%,}"; OUT="$T/results/formula_small6_sgn1.json" ;;
  r6_small6)   NAME=sst_bert_small_6;  ARGS="--n_sent 12 --pos 2 --n_sst 48 --l1_steps 400 --l1N 1 --l1rot 1 --hi 0.1 --radius_names identity,small6,cand:svd_jacN_all,cand:l1N_qk+av0,cand:l1N_rot,cand:l1N_rot_qk+av0 --n_dev 24 --dev_split test --tag _r6 --gauges $G/deept_small6_seed0.pt"; OUT="$T/results/formula_small6_r6.json" ;;
esac
mark START; "$PY" -u gauge_formula.py validate --name ${NAME:-sst_bert_small_6} $ARGS --seed ${SEED:-0} --out "$OUT" >> "$S/formula_$W.log" 2>&1; RC=$?; mark "DONE rc=$RC"; exit $RC
